name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: download cert openssl
      - run: sudo apt install -y libssl-dev
      - name: Create cert openssl
        run: openssl req -nodes -new -x509 -keyout private.key -out cert.crt -subj "/C=RU/ST=Moscow/L=Moscow/O=Codeby/OU=School/CN=codeby.local
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Binary
        run: make
      - name: Simple Test
        run: |
          ./dummy-server.bin &
          sleep 3
          curl -s -k https://localhost:8443
          kill $!
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./dummy-server.bin

